### ISSUE TITLE
Pay for what you don't use

### ISSUE THREAD

**Issue by ManDeJan** [wovo/hwlib#1]
Why is it that when I only want to say, blink a led with hwlib everything in hwlib ends up in the binary? hwlib is so big now that this is becomming an issue if I use hwlib outside of bmptk, binaries end up so big that I cannot link succesfully if I dont optimize with at least -O1.

**Comment by wovo** [comment]
?gebruik je wel

-ffunction-sections?

?


Mij Due blink is 420 bytes.


Wouter van Ooijen

0638150444 - DL200 2.86

________________________________
Van: Jan Halsema <notifications@github.com>
Verzonden: woensdag 15 februari 2017 16:13
Aan: wovo/hwlib
CC: Subscribed
Onderwerp: [wovo/hwlib] Pay for what you don't use (#1)


Why is it that when I only want to say, blink a led with hwlib everything in hwlib ends up in the binary? hwlib is so big now that this is becomming an issue if I use hwlib outside of bmptk, binaries end up so big that I cannot link succesfully if I dont optimize with at least -O1.

-
