### ISSUE TITLE
https://github.com/wovo/hwlib/commit/f05b66f15e6552cd6d1a0e3e48a589f09f51e743

### ISSUE THREAD

**Issue by CvRXX** [wovo/hwlib#2]
In this [commit](https://github.com/wovo/hwlib/commit/f05b66f15e6552cd6d1a0e3e48a589f09f51e743) multiple binaries are pushed upstream. There are also a lot of IDE specific files in the repo.

**Comment by wovo** [comment]
?Should be corrected by now in some later commit.


Wouter van Ooijen

0638150444 - DL200 2.86

________________________________
Van: Carlos van Rooijen <notifications@github.com>
Verzonden: woensdag 15 februari 2017 16:16
Aan: wovo/hwlib
CC: Subscribed
Onderwerp: [wovo/hwlib] https://github.com/wovo/hwlib/commit/f05b66f15e6552cd6d1a0e3e48a589f09f51e743 (#2)


In this commit<https://github.com/wovo/hwlib/commit/f05b66f15e6552cd6d1a0e3e48a589f09f51e743> multiple binaries are pushed upstream. There are also a lot of IDE specific files in the repo.

-

**Comment by CvRXX** [comment]
Ah great!

You do know that your phone number is know publicly published on GitHub?

**Comment by wovo** [comment]
?The HU number? That's totally public.


Wouter van Ooijen

0638150444 - DL200 2.86

________________________________
Van: Carlos van Rooijen <notifications@github.com>
Verzonden: donderdag 16 februari 2017 08:40
Aan: wovo/hwlib
CC: Wouter van Ooijen; Comment
Onderwerp: Re: [wovo/hwlib] https://github.com/wovo/hwlib/commit/f05b66f15e6552cd6d1a0e3e48a589f09f51e743 (#2)


Ah great!

You do know that your phone number is know publicly published on GitHub?

-

**Comment by CvRXX** [comment]
Oke, just so you know
