### ISSUE TITLE
hwlib not compiling

### ISSUE THREAD

**Issue by DavidStrootman** [wovo/hwlib#25]
Pull request #24  Introduces the use of sam3xa.h, but this is not included in the wovo/installers repo.
compiling with ```#include "sam3.h"``` works fine but ```#include sam3xa.h" gives the following error: 
https://pastebin.com/1CeMTsDn

**Comment by JulianvDoorn** [comment]
Besides /bmptk/targets/cortex/atmel also /bmptk/targets/cortex/atmel/Source/include should be included. This is bmptk's responsibility, this issue is already addressed in the latest version of bmptk.

Tl;dr run git pull in your bmptk

**Comment by DavidStrootman** [comment]
My bad. Copied an old version instead of installing bmptk.
