### ISSUE TITLE
Meaningless abs function in line draw

### ISSUE THREAD

**Issue by ManDeJan** [wovo/hwlib#3]
[link to code](https://github.com/wovo/hwlib/blob/master/library/hwlib-graphics.hpp#L583-L585)

```
static uint_fast16_t abs( uint_fast16_t x ){
      return x >= 0 ? x : -x;
}
```

the above function is written in the line class, however, it is meaningless as unsigned integers are always an absolute value.

**Comment by wovo** [comment]
I should have payed attention to this one, it took me some time to figure out why lines were drawn erratically. Corrected now (there were some more places where signed ints should be used insstead of unsigned).
