### ISSUE TITLE
Nested ternary operators and if statements that always result to false;

### ISSUE THREAD

**Issue by ManDeJan** [wovo/hwlib#5]
[link to code](https://github.com/wovo/hwlib/blob/master/library/hwlib-graphics.hpp#L84-L90)

```
   static constexpr uint8_t clip( uint_fast16_t x, bool transparent = false ){
      return ( transparent )
         ? 0
         : ( x < 0 ) 
            ? 0 
            : ( x > 0xFF ? 0xFF : x ); 
   }  

```
This is 3 nested ternary operators!

And one of them checks if an unsigned integer x is smaller than 0, this is always false. Could be rewritten this way:

```
static constexpr uint8_t clip(uint_fast16_t x, bool transparent = false) {    
    if (transparent)
        return 0;
    else if (x > 255)
        x = 255;
    return x;
}
```

This would do the same thing. Godbolt comparison:
https://godbolt.org/g/lcCYMT
https://godbolt.org/g/fbqGDf

**Comment by wovo** [comment]
That code fragment was changed somewhere between the issue ticket and now.
