### ISSUE TITLE
GLCD clear() does not clear entire buffer / hangs processor

### ISSUE THREAD

**Issue by cjsmeele** [wovo/hwlib#8]
504 is out of range for `uint8_t`: https://github.com/wovo/hwlib/blob/98d3aaa81079aebfc93532a8d0c13d36fd19ae43/library/hwlib-glcd-5510.hpp#L141

FWIW: `-Wtype-limits` detects this, also via `-Wextra`.

**Comment by wovo** [comment]
thanks, has been corrected.


Wouter van Ooijen

0638150444 - DL200 2.86

________________________________
Van: Chris Smeele <notifications@github.com>
Verzonden: maandag 2 oktober 2017 13:27
Aan: wovo/hwlib
CC: Subscribed
Onderwerp: [wovo/hwlib] GLCD clear() does not clear entire buffer / hangs processor (#8)


504 is out of range for uint8_t: https://github.com/wovo/hwlib/blob/98d3aaa81079aebfc93532a8d0c13d36fd19ae43/library/hwlib-glcd-5510.hpp#L141

FWIW: -Wtype-limits detects this, also via -Wextra.

-

**Comment by Bob-Thomas** [comment]
If it's resolved this issue should probably be closed :3
